### ISSUE TITLE
API: Create new route for updating survey option count for a specified option

### ISSUE THREAD

**Issue by ethanstrominger** [wat-the-duck/pollaris-surveys-api#26]
Proposed design:

Change model so that votes is a separate array of schema optionVotes.
schema optionVotes would have two fields {option: string, numVotes: number}.  Currently, numVotes is includes in options schema, but this makes it completed to update the options.

**Comment by hashbangash** [comment]
Closed with https://github.com/wat-the-duck/pollaris-surveys-api/pull/28
